/**
 * generated by Xtext 2.12.0
 */
package com.hribol.bromium.dsl.ui;

import com.hribol.bromium.dsl.ui.AbstractBromiumUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@SuppressWarnings("all")
public class BromiumUiModule extends AbstractBromiumUiModule {
  public BromiumUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
