/**
 * generated by Xtext 2.12.0
 */
package com.hribol.bromium.dsl.ui;

import com.google.inject.Binder;
import com.hribol.bromium.dsl.ui.AbstractBromiumUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.ui.editor.contentassist.XtextContentAssistProcessor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@SuppressWarnings("all")
public class BromiumUiModule extends AbstractBromiumUiModule {
	public BromiumUiModule(final AbstractUIPlugin plugin) {
		super(plugin);
	}

	@Override
	public void configure(Binder binder) {
		super.configure(binder);
		binder.bind(String.class)
				.annotatedWith(com.google.inject.name.Names
						.named((XtextContentAssistProcessor.COMPLETION_AUTO_ACTIVATION_CHARS)))
				.toInstance("ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz.;");
	}
}
