/**
 * generated by Xtext 2.13.0
 */
package com.hribol.bromium.dsl.bromium;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see com.hribol.bromium.dsl.bromium.BromiumPackage
 * @generated
 */
public interface BromiumFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  BromiumFactory eINSTANCE = com.hribol.bromium.dsl.bromium.impl.BromiumFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Model</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Model</em>'.
   * @generated
   */
  Model createModel();

  /**
   * Returns a new object of class '<em>Application Action</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Application Action</em>'.
   * @generated
   */
  ApplicationAction createApplicationAction();

  /**
   * Returns a new object of class '<em>Syntax Definition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Syntax Definition</em>'.
   * @generated
   */
  SyntaxDefinition createSyntaxDefinition();

  /**
   * Returns a new object of class '<em>Web Driver Action Condition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Web Driver Action Condition</em>'.
   * @generated
   */
  WebDriverActionCondition createWebDriverActionCondition();

  /**
   * Returns a new object of class '<em>Web Driver Action</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Web Driver Action</em>'.
   * @generated
   */
  WebDriverAction createWebDriverAction();

  /**
   * Returns a new object of class '<em>Precondition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Precondition</em>'.
   * @generated
   */
  Precondition createPrecondition();

  /**
   * Returns a new object of class '<em>Postcondition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Postcondition</em>'.
   * @generated
   */
  Postcondition createPostcondition();

  /**
   * Returns a new object of class '<em>Expect Http Request</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Expect Http Request</em>'.
   * @generated
   */
  ExpectHttpRequest createExpectHttpRequest();

  /**
   * Returns a new object of class '<em>Element By Css To Be Present</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Element By Css To Be Present</em>'.
   * @generated
   */
  ElementByCssToBePresent createElementByCssToBePresent();

  /**
   * Returns a new object of class '<em>Click Css Selector</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Click Css Selector</em>'.
   * @generated
   */
  ClickCssSelector createClickCssSelector();

  /**
   * Returns a new object of class '<em>Page Load</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Page Load</em>'.
   * @generated
   */
  PageLoad createPageLoad();

  /**
   * Returns a new object of class '<em>Type Text In Element Found By Css Selector</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Type Text In Element Found By Css Selector</em>'.
   * @generated
   */
  TypeTextInElementFoundByCssSelector createTypeTextInElementFoundByCssSelector();

  /**
   * Returns a new object of class '<em>Text Of Element With Css Selector To Be</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Text Of Element With Css Selector To Be</em>'.
   * @generated
   */
  TextOfElementWithCssSelectorToBe createTextOfElementWithCssSelectorToBe();

  /**
   * Returns a new object of class '<em>Click Class By Text</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Click Class By Text</em>'.
   * @generated
   */
  ClickClassByText createClickClassByText();

  /**
   * Returns a new object of class '<em>Set Variable To Text Of Element With Css Selector</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Set Variable To Text Of Element With Css Selector</em>'.
   * @generated
   */
  SetVariableToTextOfElementWithCssSelector createSetVariableToTextOfElementWithCssSelector();

  /**
   * Returns a new object of class '<em>Click Data Id</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Click Data Id</em>'.
   * @generated
   */
  ClickDataId createClickDataId();

  /**
   * Returns a new object of class '<em>Confirm Alert</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Confirm Alert</em>'.
   * @generated
   */
  ConfirmAlert createConfirmAlert();

  /**
   * Returns a new object of class '<em>Click Id</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Click Id</em>'.
   * @generated
   */
  ClickId createClickId();

  /**
   * Returns a new object of class '<em>Click Name</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Click Name</em>'.
   * @generated
   */
  ClickName createClickName();

  /**
   * Returns a new object of class '<em>Parameter Value</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Parameter Value</em>'.
   * @generated
   */
  ParameterValue createParameterValue();

  /**
   * Returns a new object of class '<em>Exposed Parameter</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Exposed Parameter</em>'.
   * @generated
   */
  ExposedParameter createExposedParameter();

  /**
   * Returns a new object of class '<em>Three Dotted Version</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Three Dotted Version</em>'.
   * @generated
   */
  ThreeDottedVersion createThreeDottedVersion();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  BromiumPackage getBromiumPackage();

} //BromiumFactory
