/**
 * generated by Xtext 2.13.0
 */
package com.hribol.bromium.dsl.bromium;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Click Id</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see com.hribol.bromium.dsl.bromium.BromiumPackage#getClickId()
 * @model
 * @generated
 */
public interface ClickId extends WebDriverAction
{
} // ClickId
