/**
 * generated by Xtext 2.13.0
 */
package com.hribol.bromium.dsl.bromium;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Page Load</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see com.hribol.bromium.dsl.bromium.BromiumPackage#getPageLoad()
 * @model
 * @generated
 */
public interface PageLoad extends WebDriverAction
{
} // PageLoad
