/**
 * generated by Xtext 2.13.0
 */
package com.hribol.bromium.dsl.bromium;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Set Variable To Text Of Element With Css Selector</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see com.hribol.bromium.dsl.bromium.BromiumPackage#getSetVariableToTextOfElementWithCssSelector()
 * @model
 * @generated
 */
public interface SetVariableToTextOfElementWithCssSelector extends WebDriverAction
{
} // SetVariableToTextOfElementWithCssSelector
