/**
 * generated by Xtext 2.13.0
 */
package com.hribol.bromium.dsl.bromium;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Text Of Element With Css Selector To Be</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see com.hribol.bromium.dsl.bromium.BromiumPackage#getTextOfElementWithCssSelectorToBe()
 * @model
 * @generated
 */
public interface TextOfElementWithCssSelectorToBe extends WebDriverActionCondition
{
} // TextOfElementWithCssSelectorToBe
