/**
 * generated by Xtext 2.12.0
 */
package com.hribol.bromium.dsl.bromium;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Three Dotted Version</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.hribol.bromium.dsl.bromium.ThreeDottedVersion#getBig <em>Big</em>}</li>
 *   <li>{@link com.hribol.bromium.dsl.bromium.ThreeDottedVersion#getMedium <em>Medium</em>}</li>
 *   <li>{@link com.hribol.bromium.dsl.bromium.ThreeDottedVersion#getSmall <em>Small</em>}</li>
 * </ul>
 *
 * @see com.hribol.bromium.dsl.bromium.BromiumPackage#getThreeDottedVersion()
 * @model
 * @generated
 */
public interface ThreeDottedVersion extends Version
{
  /**
   * Returns the value of the '<em><b>Big</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Big</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Big</em>' attribute.
   * @see #setBig(int)
   * @see com.hribol.bromium.dsl.bromium.BromiumPackage#getThreeDottedVersion_Big()
   * @model
   * @generated
   */
  int getBig();

  /**
   * Sets the value of the '{@link com.hribol.bromium.dsl.bromium.ThreeDottedVersion#getBig <em>Big</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Big</em>' attribute.
   * @see #getBig()
   * @generated
   */
  void setBig(int value);

  /**
   * Returns the value of the '<em><b>Medium</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Medium</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Medium</em>' attribute.
   * @see #setMedium(int)
   * @see com.hribol.bromium.dsl.bromium.BromiumPackage#getThreeDottedVersion_Medium()
   * @model
   * @generated
   */
  int getMedium();

  /**
   * Sets the value of the '{@link com.hribol.bromium.dsl.bromium.ThreeDottedVersion#getMedium <em>Medium</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Medium</em>' attribute.
   * @see #getMedium()
   * @generated
   */
  void setMedium(int value);

  /**
   * Returns the value of the '<em><b>Small</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Small</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Small</em>' attribute.
   * @see #setSmall(int)
   * @see com.hribol.bromium.dsl.bromium.BromiumPackage#getThreeDottedVersion_Small()
   * @model
   * @generated
   */
  int getSmall();

  /**
   * Sets the value of the '{@link com.hribol.bromium.dsl.bromium.ThreeDottedVersion#getSmall <em>Small</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Small</em>' attribute.
   * @see #getSmall()
   * @generated
   */
  void setSmall(int value);

} // ThreeDottedVersion
