/**
 * generated by Xtext 2.13.0
 */
package com.hribol.bromium.dsl.bromium;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Web Driver Action Condition</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * <ul>
 *   <li>{@link com.hribol.bromium.dsl.bromium.WebDriverActionCondition#getParameterNames <em>Parameter Names</em>}</li>
 *   <li>{@link com.hribol.bromium.dsl.bromium.WebDriverActionCondition#getParameterValues <em>Parameter Values</em>}</li>
 * </ul>
 * </p>
 *
 * @see com.hribol.bromium.dsl.bromium.BromiumPackage#getWebDriverActionCondition()
 * @model
 * @generated
 */
public interface WebDriverActionCondition extends EObject
{
  /**
   * Returns the value of the '<em><b>Parameter Names</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Parameter Names</em>' attribute list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Parameter Names</em>' attribute list.
   * @see com.hribol.bromium.dsl.bromium.BromiumPackage#getWebDriverActionCondition_ParameterNames()
   * @model unique="false"
   * @generated
   */
  EList<String> getParameterNames();

  /**
   * Returns the value of the '<em><b>Parameter Values</b></em>' containment reference list.
   * The list contents are of type {@link com.hribol.bromium.dsl.bromium.ParameterValue}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Parameter Values</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Parameter Values</em>' containment reference list.
   * @see com.hribol.bromium.dsl.bromium.BromiumPackage#getWebDriverActionCondition_ParameterValues()
   * @model containment="true"
   * @generated
   */
  EList<ParameterValue> getParameterValues();

} // WebDriverActionCondition
