/**
 * generated by Xtext 2.13.0
 */
package com.hribol.bromium.dsl.bromium;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Web Driver Action Condition</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see com.hribol.bromium.dsl.bromium.BromiumPackage#getWebDriverActionCondition()
 * @model
 * @generated
 */
public interface WebDriverActionCondition extends EObject
{
} // WebDriverActionCondition
