/*
 * generated by Xtext 2.12.0
 */
package com.hribol.bromium.dsl.ui

import javax.xml.bind.Binder
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor
import org.eclipse.ui.plugin.AbstractUIPlugin

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
//@FinalFieldsConstructor
class BromiumUiModule extends AbstractBromiumUiModule {
	
	new(AbstractUIPlugin plugin) {
		super(plugin)
	}

}
