/**
 * generated by Xtext 2.13.0
 */
package com.hribol.bromium.dsl.bromium.impl;

import com.hribol.bromium.dsl.bromium.BromiumPackage;
import com.hribol.bromium.dsl.bromium.ClickClassByText;
import com.hribol.bromium.dsl.bromium.ParameterValue;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Click Class By Text</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link com.hribol.bromium.dsl.bromium.impl.ClickClassByTextImpl#getCssClass <em>Css Class</em>}</li>
 *   <li>{@link com.hribol.bromium.dsl.bromium.impl.ClickClassByTextImpl#getText <em>Text</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ClickClassByTextImpl extends WebDriverActionImpl implements ClickClassByText
{
  /**
   * The cached value of the '{@link #getCssClass() <em>Css Class</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCssClass()
   * @generated
   * @ordered
   */
  protected ParameterValue cssClass;

  /**
   * The cached value of the '{@link #getText() <em>Text</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getText()
   * @generated
   * @ordered
   */
  protected ParameterValue text;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ClickClassByTextImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return BromiumPackage.Literals.CLICK_CLASS_BY_TEXT;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ParameterValue getCssClass()
  {
    return cssClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetCssClass(ParameterValue newCssClass, NotificationChain msgs)
  {
    ParameterValue oldCssClass = cssClass;
    cssClass = newCssClass;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, BromiumPackage.CLICK_CLASS_BY_TEXT__CSS_CLASS, oldCssClass, newCssClass);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setCssClass(ParameterValue newCssClass)
  {
    if (newCssClass != cssClass)
    {
      NotificationChain msgs = null;
      if (cssClass != null)
        msgs = ((InternalEObject)cssClass).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - BromiumPackage.CLICK_CLASS_BY_TEXT__CSS_CLASS, null, msgs);
      if (newCssClass != null)
        msgs = ((InternalEObject)newCssClass).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - BromiumPackage.CLICK_CLASS_BY_TEXT__CSS_CLASS, null, msgs);
      msgs = basicSetCssClass(newCssClass, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, BromiumPackage.CLICK_CLASS_BY_TEXT__CSS_CLASS, newCssClass, newCssClass));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ParameterValue getText()
  {
    return text;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetText(ParameterValue newText, NotificationChain msgs)
  {
    ParameterValue oldText = text;
    text = newText;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, BromiumPackage.CLICK_CLASS_BY_TEXT__TEXT, oldText, newText);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setText(ParameterValue newText)
  {
    if (newText != text)
    {
      NotificationChain msgs = null;
      if (text != null)
        msgs = ((InternalEObject)text).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - BromiumPackage.CLICK_CLASS_BY_TEXT__TEXT, null, msgs);
      if (newText != null)
        msgs = ((InternalEObject)newText).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - BromiumPackage.CLICK_CLASS_BY_TEXT__TEXT, null, msgs);
      msgs = basicSetText(newText, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, BromiumPackage.CLICK_CLASS_BY_TEXT__TEXT, newText, newText));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case BromiumPackage.CLICK_CLASS_BY_TEXT__CSS_CLASS:
        return basicSetCssClass(null, msgs);
      case BromiumPackage.CLICK_CLASS_BY_TEXT__TEXT:
        return basicSetText(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case BromiumPackage.CLICK_CLASS_BY_TEXT__CSS_CLASS:
        return getCssClass();
      case BromiumPackage.CLICK_CLASS_BY_TEXT__TEXT:
        return getText();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case BromiumPackage.CLICK_CLASS_BY_TEXT__CSS_CLASS:
        setCssClass((ParameterValue)newValue);
        return;
      case BromiumPackage.CLICK_CLASS_BY_TEXT__TEXT:
        setText((ParameterValue)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case BromiumPackage.CLICK_CLASS_BY_TEXT__CSS_CLASS:
        setCssClass((ParameterValue)null);
        return;
      case BromiumPackage.CLICK_CLASS_BY_TEXT__TEXT:
        setText((ParameterValue)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case BromiumPackage.CLICK_CLASS_BY_TEXT__CSS_CLASS:
        return cssClass != null;
      case BromiumPackage.CLICK_CLASS_BY_TEXT__TEXT:
        return text != null;
    }
    return super.eIsSet(featureID);
  }

} //ClickClassByTextImpl
