/**
 * generated by Xtext 2.13.0
 */
package com.hribol.bromium.dsl.bromium.impl;

import com.hribol.bromium.dsl.bromium.BromiumPackage;
import com.hribol.bromium.dsl.bromium.SetVariableToTextOfElementWithCssSelector;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Set Variable To Text Of Element With Css Selector</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class SetVariableToTextOfElementWithCssSelectorImpl extends WebDriverActionImpl implements SetVariableToTextOfElementWithCssSelector
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SetVariableToTextOfElementWithCssSelectorImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return BromiumPackage.Literals.SET_VARIABLE_TO_TEXT_OF_ELEMENT_WITH_CSS_SELECTOR;
  }

} //SetVariableToTextOfElementWithCssSelectorImpl
