/**
 * generated by Xtext 2.13.0
 */
package com.hribol.bromium.dsl.bromium.impl;

import com.hribol.bromium.dsl.bromium.BromiumPackage;
import com.hribol.bromium.dsl.bromium.TextOfElementWithCssSelectorToBe;
import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Text Of Element With Css Selector To Be</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class TextOfElementWithCssSelectorToBeImpl extends WebDriverActionConditionImpl implements TextOfElementWithCssSelectorToBe
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected TextOfElementWithCssSelectorToBeImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return BromiumPackage.Literals.TEXT_OF_ELEMENT_WITH_CSS_SELECTOR_TO_BE;
  }

} //TextOfElementWithCssSelectorToBeImpl
