/*
 * generated by Xtext 2.12.0
 */
package com.hribol.bromium.dsl.web;

import org.eclipse.xtext.web.server.DefaultWebModule;

/**
 * Manual modifications go to {@link BromiumWebModule}.
 */
@SuppressWarnings("all")
public abstract class AbstractBromiumWebModule extends DefaultWebModule {

}
