/*
 * generated by Xtext 2.13.0
 */
package com.hribol.bromium.dsl.web


/**
 * Use this class to register additional components to be used within the web application.
 */
class BromiumWebModule extends AbstractBromiumWebModule {
}
