/**
 * generated by Xtext 2.12.0
 */
package com.hribol.bromium.dsl;

import com.hribol.bromium.dsl.BromiumStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class BromiumStandaloneSetup extends BromiumStandaloneSetupGenerated {
  public static void doSetup() {
    new BromiumStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
