/**
 * generated by Xtext 2.13.0
 */
package com.hribol.bromium.dsl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import com.hribol.bromium.dsl.BromiumRuntimeModule;
import com.hribol.bromium.dsl.BromiumStandaloneSetup;
import com.hribol.bromium.dsl.ide.BromiumIdeModule;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class BromiumIdeSetup extends BromiumStandaloneSetup {
  @Override
  public Injector createInjector() {
    BromiumRuntimeModule _bromiumRuntimeModule = new BromiumRuntimeModule();
    BromiumIdeModule _bromiumIdeModule = new BromiumIdeModule();
    return Guice.createInjector(Modules2.mixin(_bromiumRuntimeModule, _bromiumIdeModule));
  }
}
