/*
 * generated by Xtext 2.13.0
 */
package com.hribol.bromium.dsl.parser.antlr;

import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

import java.io.InputStream;

public class BromiumAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("com/hribol/bromium/dsl/parser/antlr/internal/InternalBromium.tokens");
	}
}
